### ISSUE TITLE
Ascii下不能输入中文

### ISSUE THREAD

**Issue by zh3305** [qsaker/QtSwissArmyKnife#11]
在Ascii类型下 不能输入中文,粘贴的中文也消失了

**Comment by daozhixiaoyao** [comment]
yes




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qsaker/QtSwissArmyKnife"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月6日(星期五) 晚上6:50
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[qsaker/QtSwissArmyKnife] Ascii下不能输入中文 (Issue #11)





 
在Ascii类型下 不能输入中文,粘贴的中文也消失了
