### ISSUE TITLE
QtSwissArmyKnifeV3.4.1解压后Qt5.14.2 ming64编译报错打不开数据库

### ISSUE THREAD

**Issue by yanchenyuvip** [qsaker/QtSwissArmyKnife#6]
SAKApplication QSAKDatabase.sqlite3 open failed:  "unable to open database file Error opening database"
ASSERT failure in SAKApplication: "Open database failed!", file ..\QtSwissArmyKnife-3.4.1\src\SAKApplication.cc, line 103
10:18:59: 程序异常结束。

mDatabaseName = QString("%1/%2.sqlite3").arg(path).arg(qApp->applicationName());
修正为：
mDatabaseName = "mydb.db";//QString("%1/%2.sqlite3").arg(path).arg(qApp->applicationName());
正常编译通过；

**Comment by qsaker** [comment]
使用release版本编译运行即可：
![捕获](https://user-images.githubusercontent.com/43397056/104686772-d77cd680-5738-11eb-9bcd-b1ee5e6c2406.PNG)
